[general]
magicEnabled = false

[server]
enableCORS = true
port = 8501

[browser]
gatherUsageStats = false

[runner]
python_version = "3.9" 

[theme]
base="dark"
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"